/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "inverse-primary": "#e4c600",
        "outline-variant": "#cfc6ab",
        "secondary-fixed": "#e5e2e1",
        "on-primary": "#ffffff",
        "primary-container": "#ffdd00",
        "on-secondary-fixed": "#1b1b1c",
        "surface-bright": "#fcf9f8",
        "on-secondary-container": "#636262",
        "on-primary-container": "#716100",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#ece900",
        "tertiary": "#636100",
        "surface-tint": "#6d5e00",
        "on-error": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-tertiary-fixed": "#1d1d00",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed": "#ffe251",
        "tertiary-fixed-dim": "#cfcc00",
        "secondary-fixed-dim": "#c8c6c5",
        "surface": "#fcf9f8",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed-variant": "#474746",
        "surface-dim": "#dcd9d9",
        "primary-fixed-dim": "#e4c600",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#303030",
        "on-tertiary-container": "#666500",
        "on-surface": "#1b1b1c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#e8e500",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#7e775f",
        "primary": "#6d5e00",
        "on-background": "#1b1b1c",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#211b00",
        "on-tertiary-fixed-variant": "#4a4900",
        "secondary": "#5f5e5e",
        "background": "#fcf9f8",
        "on-primary-fixed-variant": "#524600",
        "surface-container-high": "#eae7e7",
        "on-surface-variant": "#4c4732"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
