/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":                    "rgb(var(--background) / <alpha-value>)",
        "on-background":                 "rgb(var(--on_background) / <alpha-value>)",
        "surface":                       "rgb(var(--surface) / <alpha-value>)",
        "surface-container":             "rgb(var(--surface_container) / <alpha-value>)",
        "surface-container-low":         "rgb(var(--surface_container_low) / <alpha-value>)",
        "surface-container-high":        "rgb(var(--surface_container_high) / <alpha-value>)",
        "surface-container-highest":     "rgb(var(--surface_container_highest) / <alpha-value>)",
        "surface-container-lowest":      "rgb(var(--surface_container_lowest) / <alpha-value>)",
        "surface-bright":                "rgb(var(--surface_bright) / <alpha-value>)",
        "surface-dim":                   "rgb(var(--surface_dim) / <alpha-value>)",
        "surface-variant":               "rgb(var(--surface_variant) / <alpha-value>)",
        "surface-tint":                  "rgb(var(--surface_tint) / <alpha-value>)",
        "primary":                       "rgb(var(--primary) / <alpha-value>)",
        "primary-container":             "rgb(var(--primary_container) / <alpha-value>)",
        "on-primary":                    "rgb(var(--on_primary) / <alpha-value>)",
        "on-primary-container":          "rgb(var(--on_primary_container) / <alpha-value>)",
        "primary-fixed":                 "rgb(var(--primary_fixed) / <alpha-value>)",
        "primary-fixed-dim":             "rgb(var(--primary_fixed_dim) / <alpha-value>)",
        "on-primary-fixed":              "rgb(var(--on_primary_fixed) / <alpha-value>)",
        "on-primary-fixed-variant":      "rgb(var(--on_primary_fixed_variant) / <alpha-value>)",
        "inverse-primary":               "rgb(var(--inverse_primary) / <alpha-value>)",
        "secondary":                     "rgb(var(--secondary) / <alpha-value>)",
        "secondary-container":           "rgb(var(--secondary_container) / <alpha-value>)",
        "on-secondary":                  "rgb(var(--on_secondary) / <alpha-value>)",
        "on-secondary-container":        "rgb(var(--on_secondary_container) / <alpha-value>)",
        "secondary-fixed":               "rgb(var(--secondary_fixed) / <alpha-value>)",
        "secondary-fixed-dim":           "rgb(var(--secondary_fixed_dim) / <alpha-value>)",
        "on-secondary-fixed":            "rgb(var(--on_secondary_fixed) / <alpha-value>)",
        "on-secondary-fixed-variant":    "rgb(var(--on_secondary_fixed_variant) / <alpha-value>)",
        "tertiary":                      "rgb(var(--tertiary) / <alpha-value>)",
        "tertiary-container":            "rgb(var(--tertiary_container) / <alpha-value>)",
        "on-tertiary":                   "rgb(var(--on_tertiary) / <alpha-value>)",
        "on-tertiary-container":         "rgb(var(--on_tertiary_container) / <alpha-value>)",
        "tertiary-fixed":                "rgb(var(--tertiary_fixed) / <alpha-value>)",
        "tertiary-fixed-dim":            "rgb(var(--tertiary_fixed_dim) / <alpha-value>)",
        "on-tertiary-fixed":             "rgb(var(--on_tertiary_fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant":     "rgb(var(--on_tertiary_fixed_variant) / <alpha-value>)",
        "error":                         "rgb(var(--error) / <alpha-value>)",
        "error-container":               "rgb(var(--error_container) / <alpha-value>)",
        "on-error":                      "rgb(var(--on_error) / <alpha-value>)",
        "on-error-container":            "rgb(var(--on_error_container) / <alpha-value>)",
        "outline":                       "rgb(var(--outline) / <alpha-value>)",
        "outline-variant":               "rgb(var(--outline_variant) / <alpha-value>)",
        "on-surface":                    "rgb(var(--on_surface) / <alpha-value>)",
        "on-surface-variant":            "rgb(var(--on_surface_variant) / <alpha-value>)",
        "inverse-surface":               "rgb(var(--inverse_surface) / <alpha-value>)",
        "inverse-on-surface":            "rgb(var(--inverse_on_surface) / <alpha-value>)",
      },
      fontFamily: {
        "headline": ["Outfit", "sans-serif"],
        "body": ["DM Sans", "sans-serif"],
        "label": ["DM Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
